#!/bin/bash
# Assumes "1 2 3 4 5 6" cwd by default
#Culminates wavefunctions and stores them ready for HPC or Jnana to grab them

[ -z "$1" ] && toRun=(1 2 3 4 5 6) || toRun=($1)
[ -z "$2" ] && folder=${PWD##*/} || folder=$2

mkdir /short/h72/tim/qfdtd/store/$folder

for i in "${toRun[@]}"
do
    case $i in
    1)
        name=wfnGS
        state=gs ;;
    2)
        name=wfnES1
        state=es1 ;;
    3)
        name=wfnES2
        state=es2 ;;
    4)
        name=wfnES3
        state=es3 ;;
    5)
        name=wfnES4
        state=es4 ;;
    6)
        name=wfnES5
        state=es5 ;;
    esac

    #grab largest *.job.* for directory
    cd $state
    cp $(find . -maxdepth 1 -type f -name "$name.*.job.o" | tail -n 1) ../$state.job.o
    cd ..
    
    if [ $i -gt 1 ]
    then
        #Rename wavefunction files in each dir from _0_* to _N_*
        for file in $state/data/wavefunction_0_*; do mv $file "${file/_0_/_$((i-1))_}"; done
    fi

    #send wavefunction files to the store
    mv $state/data/wavefunction*.dat /short/h72/tim/qfdtd/store/$folder/
done

#send parameter files
cp *.job.o params.txt /short/h72/tim/qfdtd/store/$folder/
[ -e gs/cluster.xyz ] && cp gs/cluster.xyz /short/h72/tim/qfdtd/store/$folder/

#remove temp files
rm *.job.o

echo "Files succesfully stored in /short/h72/tim/qfdtd/store/"$folder"/"

