#!/bin/bash
# Sets up new run from matlab data. Assumes "1 2 3 4 5 6" common by default

echo "Have you changed params.txt? (Enter to continue, Ctrl+C to stop)"
read


[ -z "$1" ] && toRun=(1 2 3 4 5 6) || toRun=($1)
[ -z "$2" ] && folder=common || folder=$2

mkdir $folder
cp params.txt completeJob $folder
cd $folder


for i in "${toRun[@]}"
do
    case $i in
    1)
        lvl=one
        state=gs ;;
    2)
        lvl=two
        state=es1 ;;
    3)
        lvl=three
        state=es2 ;;
    4)
        lvl=four
        state=es3 ;;
    5)
        lvl=five
        state=es4 ;;
    6)
        lvl=six
        state=es5 ;;
    esac

    #Build directory tree and copy files
    mkdir -p $state/data/snapshot
    mkdir -p $state/debug
    ln params.txt $state/params.txt
    cp ../mpisolve $state/
    [ -e ../cluster.xyz ] && cp ../cluster.xyz $state/
    cp ../wavefn.job $state/$state.job

    nodes=$(($(ls ../staging/$lvl/ | wc -l)+1))

    mv ../staging/$lvl/*.dat $state/data/ #set up input
   
    #Submit scripts need correct CPU numbers 
    sed -i 's/np.*mpi/np '$nodes' mpi/' $state/$state.job
    sed -i 's/ncpus=.*$/ncpus='$nodes'/' $state/$state.job
    sed -i 's/-N wfn.*$/-N wfn'${state^^}'/' $state/$state.job
    
    #Submit job    
    cd $state; qsub $state.job; cd ..
done

echo "Done."
